version: "3.1"

services:
  db:
    image: mysql:8.4.2
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: teste123
  app:
    image: node:20.11.0
    ports:
      - 8081:8081
    working_dir: /app
    volumes:
      - ./:/app
    command: "npm run dev"



